version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories:
      - /docker/hami-dra-webhook
      - /docker/hami-dra-monitor
      - /docker/hami-dra-fake-driver
    schedule:
      interval: weekly
