{{- if not .Values.certs.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hami-dra-webhook.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "certs.custom.crt is required when certManager is disabled" .Values.certs.custom.crt | b64enc }}
  tls.key: {{ required "certs.custom.key is required when certManager is disabled" .Values.certs.custom.key | b64enc }}
{{- end }}
